# Generated by Django 2.2.3 on 2019-09-07 21:54

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('project_budget', models.CharField(max_length=120)),
                ('completion_date', models.CharField(blank=True, choices=[('As soon as posible', 'As soon as posible'), ('In 7 days', 'In 7 days'), ('In 15 days', 'In 15 days'), ('In 30 days', 'In 30 days'), ('Not sure/To be determined/Talk you later', 'Not sure/To be determined/Talk you later')], default='Not sure/To be determined/Talk you later', max_length=32, null=True)),
                ('project_detail', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default='I want to work with you. Possible?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.FileField(upload_to=contact.models.social_contact_icon_path)),
                ('position', models.IntegerField(default='1')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-timestamp'],
            },
        ),
    ]
